name: Sync with Upstream

on:
  schedule:
    - cron: '15 0 * * *' # 매일 자정(UTC 기준)에 실행
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout forked repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        token: ${{ secrets.GH_PAT }}

    - name: Configure git
      run: |
        git config --global user.name 'keinn51'
        git config --global user.email 'soogood97@gmail.com'

    - name: Add remote upstream
      run: git remote add upstream https://github.com/toy-project-kyungsle/bundle-repo.git

    - name: Fetch changes from upstream
      run: git fetch upstream

    - name: Merge changes from upstream/main to main
      run: |
        git checkout main
        git merge upstream/main --allow-unrelated-histories
        git push origin main
